-- Database Schema (PostgreSQL)

-- Users Table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    phone_number TEXT, -- Added for contact info
    role VARCHAR(20) NOT NULL CHECK (role IN ('doctor', 'patient')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Doctor Profiles
CREATE TABLE doctor_profiles (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    license_number TEXT UNIQUE, -- Corresponds to doctor_id string
    specialty VARCHAR(100), -- Corresponds to specialization
    bio TEXT,
    availability_config JSONB -- e.g., {"timings": ["09:00", "10:00"]} (array of time slots)
);

-- Appointments
CREATE TABLE appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID REFERENCES users(id),
    doctor_id UUID REFERENCES users(id),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'ongoing', 'completed', 'cancelled')),
    urgency_level VARCHAR(20) DEFAULT 'NORMAL' CHECK (urgency_level IN ('NORMAL', 'MEDIUM', 'HIGH', 'EMERGENCY')),
    original_start_time TIMESTAMP WITH TIME ZONE, -- Track if moved
    reschedule_reason TEXT, -- Why it was moved
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Notifications System
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    message TEXT NOT NULL,
    type VARCHAR(20) CHECK (type IN ('info', 'warning', 'emergency')),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pre-Consultation Forms
CREATE TABLE intake_forms (
    appointment_id UUID PRIMARY KEY REFERENCES appointments(id) ON DELETE CASCADE,
    -- Snapshot / Guest Details
    patient_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    email TEXT NOT NULL,
    -- Medical Info
    symptom TEXT NOT NULL, -- "Current Symptoms"
    duration VARCHAR(50),
    severity INT CHECK (severity BETWEEN 1 AND 5),
    history TEXT -- "Medical History"
);

-- Consultations (Notes & Summary)
CREATE TABLE consultation_records (
    appointment_id UUID PRIMARY KEY REFERENCES appointments(id) ON DELETE CASCADE,
    diagnosis TEXT,
    advice TEXT,
    medicines JSONB, -- Array of { name, dosage, duration }
    notes TEXT, -- Private doctor notes
    summary TEXT, -- AI generated summary
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chat Messages
CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id UUID REFERENCES appointments(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES users(id),
    content TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_appointments_patient ON appointments(patient_id);
CREATE INDEX idx_appointments_doctor ON appointments(doctor_id);
CREATE INDEX idx_appointments_date ON appointments(start_time);
CREATE INDEX idx_chat_appointment ON chat_messages(appointment_id, sent_at);
